
services:
  web:
    container_name: wright_research_web
    image: wright_research_web:latest
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DEBUG=True
      - IMAP_SERVER=imap.gmail.com
      - IMAP_PORT=993
      - IMAP_USERNAME=
      - IMAP_PASSWORD=
      - SAVE_DIR=data/emls
# command: sleep infinity 
